# Generated by Django 3.1.7 on 2021-04-12 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20210412_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='area',
            field=models.CharField(choices=[('B', 'business contest'), ('T', 'technology contest'), ('S', 'sports'), ('D', 'debate competition')], default='B', max_length=80),
        ),
        migrations.AlterField(
            model_name='contest',
            name='enddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contest',
            name='regi_ddl',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
