# Generated by Django 3.1.7 on 2021-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20210413_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='con_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='contest_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='upload',
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(default='Omitted'),
        ),
        migrations.AddField(
            model_name='contest',
            name='highlight',
            field=models.TextField(default='Good contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='requirement',
            field=models.TextField(default='Everyone is welcome'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='area',
            field=models.CharField(choices=[('B', 'business'), ('I', 'investment'), ('T', 'technology'), ('H', 'hackson'), ('M', 'mathematics'), ('S', 'sports'), ('D', 'debate'), ('C', 'cooking')], default='B', max_length=80),
        ),
    ]
