# Generated by Django 3.1.7 on 2021-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20210413_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='holder_email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='holder_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
