# Generated by Django 3.1.7 on 2021-04-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20210413_2320'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tannounce',
            new_name='announce',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamrequirement',
            new_name='requirement',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='graduationyear',
            new_name='graduationtime',
        ),
        migrations.RemoveField(
            model_name='team',
            name='contestbelonging',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamembers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tresult',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intestedarea',
        ),
        migrations.AddField(
            model_name='team',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='interestedContest',
            field=models.ManyToManyField(blank=True, related_name='interestedContest', to='contest.Contest'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.team')),
            ],
        ),
    ]
