# Generated by Django 3.1.7 on 2021-04-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210414_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('Business', 'Business'), ('Quantitative Finance & Risk Management', 'Quantitative Finance & Risk Management'), ('Math', 'Math'), ('Fintech', 'Fintech'), ('Computer Science', 'Computer Science'), ('Law', 'Law'), ('Communication', 'Communication'), ('Science', 'Science'), ('Language', 'Language')], max_length=128),
        ),
    ]
